arqlido1 = input ('Primeiro arquivo: ')
arqlido2 = input ('Segundo arquivo: ')

print ('=' * 50)
print (f'Mostrando {arqlido1}: ')
arq1 = open (arqlido1, 'r')
lendo1 = arq1.readline()
while lendo1:
    print (lendo1, end= '')
    lendo1 = arq1.readline()
arq1.close()
print ()
print ('=' * 50)
print (f'Mostrando {arqlido2}: ')
arq2 = open (arqlido2, 'r')
lendo2 = arq2.readline()
while lendo2:
    print (lendo2, end = '')
    lendo2 = arq2.readline()
arq2.close()
print ()
print ('=' * 50)
print (f'Fusão de {arqlido1} com {arqlido2}: ')
arq1 = open (arqlido1, 'r')
lendo1 = arq1.readline()
arq2 = open (arqlido2, 'r')
lendo2 = arq2.readline()
arq3 = open ('fusao.txt', 'w')
editando3 = arq3.write(lendo1)
editando3 = arq3.write(lendo2)
arq1.close()
arq2.close()
arq3.close()
arq3 = open ('fusao.txt', 'r')
lendo3 = arq3.readline()
while lendo3:
    print (lendo3, end = '')
    lendo3 = arq3.readline()
arq3.close()
print ()
print ('=' * 50)
print ('ENCERRADO')